import { LegalPage, type LegalSection } from "@/components/legal/LegalPage";

const sections: LegalSection[] = [
  {
    id: "eligibility",
    title: "1. Eligibility",
    body: (
      <>
        <p>You must be at least 18 years old to create a Velari account or use Velari&#39;s personalized services.</p>
        <p>By using Velari, you represent that you have the legal capacity to enter into these Terms.</p>
      </>
    ),
  },
  {
    id: "what-velari-provides",
    title: "2. What Velari Provides",
    body: (
      <>
        <p>Velari is a travel discovery and personalization platform designed to help users identify destinations, accommodations, experiences, and itinerary ideas based on their individual travel preferences and Emotional Travel™ profile.</p>
        <p>Velari&#39;s services may include:</p>
        <ul>
          <li>The Emotional Travel™ Assessment</li>
          <li>Emotional Travel™ profiles</li>
          <li>Personalized destination matching</li>
          <li>Accommodation recommendations</li>
          <li>Experience recommendations</li>
          <li>Wellness travel recommendations</li>
          <li>Travel inspiration</li>
          <li>Sample itineraries</li>
          <li>Personalized itinerary planning</li>
          <li>AI-assisted travel recommendations</li>
          <li>Links or connections to third-party travel providers</li>
        </ul>
        <p>Features may change, expand, or be discontinued over time.</p>
      </>
    ),
  },
  {
    id: "emotional-travel-assessment",
    title: "3. Emotional Travel™ Assessment",
    body: (
      <>
        <p>The Emotional Travel™ Assessment is designed solely for travel personalization.</p>
        <p>The Assessment may ask about your emotional priorities, travel motivations, interests, preferences, desired experiences, budget, pace, environment, or other factors relevant to travel planning.</p>
        <p>There are no medically or psychologically &quot;correct&quot; answers.</p>
        <p>The Emotional Travel™ Assessment is not:</p>
        <ul>
          <li>A psychological evaluation</li>
          <li>A mental health assessment</li>
          <li>A medical assessment</li>
          <li>A diagnostic tool</li>
          <li>Therapy</li>
          <li>Medical or psychological advice</li>
        </ul>
        <p>Velari does not diagnose or treat medical or mental health conditions.</p>
        <p>If you have concerns about your physical or mental health, you should consult an appropriate licensed professional.</p>
      </>
    ),
  },
  {
    id: "artificial-intelligence",
    title: "4. Artificial Intelligence",
    body: (
      <>
        <p>Velari uses artificial intelligence and automated technologies to help analyze preferences and generate personalized travel recommendations.</p>
        <p>AI-generated information may occasionally be incomplete, inaccurate, outdated, or unsuitable for a particular traveler.</p>
        <p>Velari does not guarantee that:</p>
        <ul>
          <li>A destination will produce a particular emotional outcome</li>
          <li>A recommended experience will be appropriate for every traveler</li>
          <li>Information generated by AI will always be accurate</li>
          <li>Recommended pricing will remain available</li>
          <li>Hotels, activities, restaurants, or experiences will remain available</li>
          <li>Travel conditions will remain unchanged</li>
        </ul>
        <p>Users should independently verify important travel information before making reservations or travel decisions.</p>
      </>
    ),
  },
  {
    id: "emotional-outcomes",
    title: "5. Emotional Outcomes",
    body: (
      <>
        <p>Velari designs recommendations around what users say they hope to experience or gain from travel.</p>
        <p>Travel experiences are subjective.</p>
        <p>Velari does not guarantee that any destination, accommodation, experience, or itinerary will cause a particular emotional, psychological, wellness, or personal outcome.</p>
        <p>Terms such as &quot;restoration,&quot; &quot;clarity,&quot; &quot;connection,&quot; &quot;discovery,&quot; &quot;adventure,&quot; or similar concepts describe travel goals and preferences, not guaranteed outcomes.</p>
      </>
    ),
  },
  {
    id: "optional-astrology-features",
    title: "6. Optional Astrology Features",
    body: (
      <>
        <p>Velari may provide optional astrology-based personalization features.</p>
        <p>Participation is voluntary.</p>
        <p>Astrology information is provided for personalization, entertainment, and travel-inspiration purposes. It should not be interpreted as scientific, medical, psychological, financial, legal, or professional advice.</p>
        <p>Users are not required to provide astrology or birth information in order to use Velari&#39;s core Emotional Travel™ services.</p>
      </>
    ),
  },
  {
    id: "travel-recommendations",
    title: "7. Travel Recommendations",
    body: (
      <>
        <p>Velari&#39;s recommendations are intended to assist with travel discovery and planning.</p>
        <p>Recommendations may be based on:</p>
        <ul>
          <li>Information you provide</li>
          <li>Your Emotional Travel™ profile</li>
          <li>Travel preferences</li>
          <li>Budget</li>
          <li>Timing</li>
          <li>Interests</li>
          <li>Destination characteristics</li>
          <li>Third-party information</li>
          <li>Automated analysis</li>
          <li>AI-generated information</li>
        </ul>
        <p>Travel information can change quickly.</p>
        <p>You are responsible for verifying important information before making travel arrangements, including:</p>
        <ul>
          <li>Prices</li>
          <li>Availability</li>
          <li>Operating hours</li>
          <li>Visa requirements</li>
          <li>Passport requirements</li>
          <li>Entry requirements</li>
          <li>Health requirements</li>
          <li>Local laws</li>
          <li>Safety conditions</li>
          <li>Accessibility</li>
          <li>Dietary accommodations</li>
          <li>Cancellation policies</li>
        </ul>
      </>
    ),
  },
  {
    id: "travel-booking",
    title: "8. Travel Booking",
    body: (
      <>
        <p>Unless expressly stated otherwise within the Velari platform, Velari currently provides travel discovery, planning, and recommendation services and does not directly operate airlines, hotels, resorts, tour companies, transportation companies, restaurants, or experience providers.</p>
        <p>Velari may provide links or connections to third-party companies through which travel services can be purchased.</p>
        <p>If you make a reservation or purchase through a third party, your transaction is between you and that provider.</p>
        <p>The third party&#39;s:</p>
        <ul>
          <li>Terms</li>
          <li>Pricing</li>
          <li>Cancellation policies</li>
          <li>Refund policies</li>
          <li>Privacy policies</li>
          <li>Availability</li>
          <li>Service obligations</li>
        </ul>
        <p>will apply to that transaction.</p>
        <p>Velari is not responsible for the acts, omissions, cancellations, service failures, or policies of independent third-party travel providers.</p>
        <p>If Velari introduces direct booking or payment services in the future, the applicable terms will be clearly disclosed before a user completes a transaction.</p>
      </>
    ),
  },
  {
    id: "pricing",
    title: "9. Pricing",
    body: (
      <>
        <p>The Emotional Travel™ Assessment and initial destination discovery are currently offered without charge.</p>
        <p>Velari may introduce paid products, premium features, personalized itinerary services, subscriptions, booking services, or other paid offerings in the future.</p>
        <p>If a service requires payment, the applicable price and material purchase terms will be displayed before you complete the purchase.</p>
        <p>Velari will not charge you solely for completing the free Emotional Travel™ Assessment unless you affirmatively choose a paid service.</p>
      </>
    ),
  },
  {
    id: "accounts",
    title: "10. Accounts",
    body: (
      <>
        <p>Certain Velari features require an account.</p>
        <p>You agree to:</p>
        <ul>
          <li>Provide accurate account information</li>
          <li>Keep your login credentials confidential</li>
          <li>Maintain accurate contact information</li>
          <li>Notify Velari of suspected unauthorized account access</li>
          <li>Accept responsibility for activity occurring through your account to the extent permitted by law</li>
        </ul>
        <p>You may not create an account using another person&#39;s identity without authorization.</p>
      </>
    ),
  },
  {
    id: "account-deletion",
    title: "11. Account Deletion",
    body: (
      <>
        <p>You may request deletion of your account at any time by contacting:</p>
        <p><a href="mailto:hello@velaritravel.com">hello@velaritravel.com</a></p>
        <p>Deletion will be handled in accordance with our Privacy Policy and applicable legal or record-retention obligations.</p>
      </>
    ),
  },
  {
    id: "acceptable-use",
    title: "12. Acceptable Use",
    body: (
      <>
        <p>You may not use Velari to:</p>
        <ul>
          <li>Violate any applicable law</li>
          <li>Attempt to gain unauthorized access to Velari systems</li>
          <li>Interfere with the operation or security of the platform</li>
          <li>Introduce malware or malicious code</li>
          <li>Scrape or systematically extract Velari content without permission</li>
          <li>Reverse engineer or attempt to replicate Velari&#39;s proprietary technology except where legally permitted</li>
          <li>Misrepresent your identity</li>
          <li>Use Velari to harm, harass, defraud, or impersonate another person</li>
          <li>Use Velari&#39;s content or technology to build a substantially competing service without authorization</li>
          <li>Circumvent security, usage, or account restrictions</li>
        </ul>
        <p>We may suspend or terminate access for violations of these Terms.</p>
      </>
    ),
  },
  {
    id: "your-information-and-content",
    title: "13. Your Information and Content",
    body: (
      <>
        <p>You retain ownership of information and content you submit to Velari.</p>
        <p>You grant Velari a limited right to process, store, reproduce, and use that information as reasonably necessary to:</p>
        <ul>
          <li>Operate the service</li>
          <li>Create your Emotional Travel™ profile</li>
          <li>Generate recommendations</li>
          <li>Maintain your account</li>
          <li>Provide requested features</li>
          <li>Improve and secure the service</li>
        </ul>
        <p>Our handling of personal information is governed by our <a href="/privacy-policy">Privacy Policy</a>.</p>
      </>
    ),
  },
  {
    id: "velari-intellectual-property",
    title: "14. Velari Intellectual Property",
    body: (
      <>
        <p>Velari and its associated content, branding, technology, designs, software, methodologies, and original materials are owned by or licensed to Velari and are protected by applicable intellectual-property laws.</p>
        <p>This includes, where applicable:</p>
        <ul>
          <li>Velari</li>
          <li>Velari Travel</li>
          <li>Emotional Travel™</li>
          <li>Assessment structure and methodology</li>
          <li>Recommendation systems</li>
          <li>Website designs</li>
          <li>Original written content</li>
          <li>Software</li>
          <li>Graphics</li>
          <li>Logos</li>
        </ul>
        <p>Your use of Velari does not grant you ownership of Velari intellectual property.</p>
        <p>You may use Velari only for lawful personal purposes unless Velari provides written permission for another use.</p>
      </>
    ),
  },
  {
    id: "third-party-content-and-services",
    title: "15. Third-Party Content and Services",
    body: (
      <>
        <p>Velari may reference or link to third-party:</p>
        <ul>
          <li>Hotels</li>
          <li>Resorts</li>
          <li>Airlines</li>
          <li>Restaurants</li>
          <li>Tour operators</li>
          <li>Activities</li>
          <li>Booking services</li>
          <li>Travel websites</li>
          <li>Destination resources</li>
          <li>Other products or services</li>
        </ul>
        <p>A recommendation or link does not guarantee or warrant the quality, availability, safety, price, accuracy, or suitability of a third-party service.</p>
        <p>Third-party services operate independently from Velari.</p>
      </>
    ),
  },
  {
    id: "travel-risks",
    title: "16. Travel Risks",
    body: (
      <>
        <p>Travel inherently involves risks and uncertainties.</p>
        <p>Conditions involving weather, transportation, political events, health, natural disasters, local regulations, strikes, closures, crime, or other circumstances may change without notice.</p>
        <p>Users are responsible for evaluating current conditions and determining whether travel is appropriate for them.</p>
        <p>Where appropriate, travelers should review information from airlines, destination authorities, healthcare professionals, government travel advisories, and other authoritative sources before traveling.</p>
      </>
    ),
  },
  {
    id: "no-professional-advice",
    title: "17. No Professional Advice",
    body: (
      <>
        <p>Information provided through Velari is intended for travel planning and informational purposes.</p>
        <p>Velari does not provide:</p>
        <ul>
          <li>Medical advice</li>
          <li>Mental health advice</li>
          <li>Legal advice</li>
          <li>Financial advice</li>
          <li>Immigration advice</li>
          <li>Safety guarantees</li>
        </ul>
        <p>Users should consult appropriate professionals or authorities when professional guidance is required.</p>
      </>
    ),
  },
  {
    id: "disclaimer-of-warranties",
    title: "18. Disclaimer of Warranties",
    body: (
      <>
        <p>To the fullest extent permitted by law, Velari is provided on an &quot;as is&quot; and &quot;as available&quot; basis.</p>
        <p>Velari does not guarantee that the service will:</p>
        <ul>
          <li>Always be available</li>
          <li>Operate without interruption</li>
          <li>Be free from errors</li>
          <li>Produce perfect recommendations</li>
          <li>Meet every user&#39;s expectations</li>
          <li>Contain completely accurate third-party information</li>
        </ul>
        <p>Nothing in these Terms excludes rights or warranties that cannot legally be excluded.</p>
      </>
    ),
  },
  {
    id: "limitation-of-liability",
    title: "19. Limitation of Liability",
    body: (
      <>
        <p>To the fullest extent permitted by applicable law, Velari will not be liable for indirect, incidental, special, consequential, or punitive damages arising from your use of the service.</p>
        <p>Velari is not responsible for losses arising from the acts, omissions, cancellations, failures, pricing, availability, safety, or policies of independent third-party travel providers.</p>
        <p>Nothing in these Terms limits liability where such limitation is prohibited by law.</p>
      </>
    ),
  },
  {
    id: "indemnification",
    title: "20. Indemnification",
    body: (
      <>
        <p>To the extent permitted by law, you agree to indemnify and hold Velari harmless from claims, liabilities, damages, or reasonable expenses resulting from your unlawful use of Velari, violation of these Terms, or infringement of the rights of another person.</p>
      </>
    ),
  },
  {
    id: "suspension-and-termination",
    title: "21. Suspension and Termination",
    body: (
      <>
        <p>Velari may suspend or terminate access to the platform if we reasonably believe that:</p>
        <ul>
          <li>These Terms have been violated</li>
          <li>The platform is being abused</li>
          <li>Fraudulent or unlawful activity is occurring</li>
          <li>Continued access creates a security or legal risk</li>
        </ul>
        <p>You may stop using Velari or request deletion of your account at any time.</p>
      </>
    ),
  },
  {
    id: "changes-to-velari",
    title: "22. Changes to Velari",
    body: (
      <>
        <p>Velari is an evolving platform.</p>
        <p>We may add, remove, modify, or discontinue features as the service develops.</p>
        <p>Where required by law, users will receive appropriate notice of material changes affecting their rights.</p>
      </>
    ),
  },
  {
    id: "changes-to-these-terms",
    title: "23. Changes to These Terms",
    body: (
      <>
        <p>We may update these Terms from time to time.</p>
        <p>The effective date at the top of the Terms will indicate when they were most recently revised.</p>
        <p>Material changes will be communicated where required by applicable law.</p>
        <p>Continued use of Velari after updated Terms become effective constitutes acceptance to the extent permitted by law.</p>
      </>
    ),
  },
  {
    id: "governing-law",
    title: "24. Governing Law",
    body: (
      <>
        <p>These Terms are governed by the laws of the State of Texas, without regard to conflict-of-law principles, except where applicable consumer-protection law requires otherwise.</p>
        <p>Any legal proceeding that is not otherwise subject to a legally required jurisdiction will be brought in a state or federal court in Texas having jurisdiction over the dispute.</p>
      </>
    ),
  },
  {
    id: "severability",
    title: "25. Severability",
    body: (
      <>
        <p>If any provision of these Terms is determined to be invalid or unenforceable, the remaining provisions will remain in effect to the fullest extent permitted by law.</p>
      </>
    ),
  },
  {
    id: "entire-agreement",
    title: "26. Entire Agreement",
    body: (
      <>
        <p>These Terms, together with the Privacy Policy and any additional terms presented for a specific Velari service, constitute the agreement between you and Velari concerning your use of the service.</p>
      </>
    ),
  },
  {
    id: "contact",
    title: "27. Contact",
    body: (
      <>
        <p>Questions regarding these Terms may be directed to:</p>
        <p>Velari Travel</p>
        <p>Email: <a href="mailto:hello@velaritravel.com">hello@velaritravel.com</a></p>
        <p>Phone: (830) 433-7323</p>
      </>
    ),
  },
];

export default function TermsOfServiceContainer() {
  return (
    <LegalPage
      title="Terms of Service"
      eyebrow="Legal"
      description="The terms governing your access to and use of Velari Travel."
      updated="September 18, 2026"
      dateLabel="Effective Date"
      stickyHero
      contactEmail="hello@velaritravel.com"
      contactLabel="these Terms"
      introduction={
        <>
          <p>These Terms of Service (&quot;Terms&quot;) govern your access to and use of VelariTravel.com and the services provided by Velari Travel (&quot;Velari,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;).</p>
          <p>By accessing Velari, creating an account, completing the Emotional Travel™ Assessment, or using our services, you agree to these Terms and our Privacy Policy.</p>
          <p>If you do not agree with these Terms, please do not use Velari.</p>
        </>
      }
      sections={sections}
    />
  );
}
